// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgGav01IafoLQgXVmXB7ffm2QEjaSYIVc',
    appId: '1:816823883322:web:950af1ef634ee70f294703',
    messagingSenderId: '816823883322',
    projectId: 'klinik-2d7c4',
    authDomain: 'klinik-2d7c4.firebaseapp.com',
    storageBucket: 'klinik-2d7c4.firebasestorage.app',
    measurementId: 'G-PZ4XS2626L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG2ft9ujA9T_ls1cFBeQyP5PHeb3ik_v8',
    appId: '1:816823883322:android:a06d6180f07cdf0c294703',
    messagingSenderId: '816823883322',
    projectId: 'klinik-2d7c4',
    storageBucket: 'klinik-2d7c4.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClalHnLk1n37hiivwmbNP1BTQqtVvBo4Y',
    appId: '1:816823883322:ios:91ba243899bef45b294703',
    messagingSenderId: '816823883322',
    projectId: 'klinik-2d7c4',
    storageBucket: 'klinik-2d7c4.firebasestorage.app',
    iosBundleId: 'com.ubsi.klinik.klinikApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClalHnLk1n37hiivwmbNP1BTQqtVvBo4Y',
    appId: '1:816823883322:ios:91ba243899bef45b294703',
    messagingSenderId: '816823883322',
    projectId: 'klinik-2d7c4',
    storageBucket: 'klinik-2d7c4.firebasestorage.app',
    iosBundleId: 'com.ubsi.klinik.klinikApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgGav01IafoLQgXVmXB7ffm2QEjaSYIVc',
    appId: '1:816823883322:web:9531238935227899294703',
    messagingSenderId: '816823883322',
    projectId: 'klinik-2d7c4',
    authDomain: 'klinik-2d7c4.firebaseapp.com',
    storageBucket: 'klinik-2d7c4.firebasestorage.app',
    measurementId: 'G-GMPMTC7L5J',
  );
}
